/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EatdoRouteImport } from './routes/_eatdo'
import { Route as GroundsRouteImport } from './routes/_grounds'
import { Route as HabitatRouteImport } from './routes/_habitat'
import { Route as RoomsRouteImport } from './routes/_rooms'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as EatdoEatdoRouteImport } from './routes/_eatdo.eatdo'
import { Route as EatdoHikingRouteImport } from './routes/_eatdo.hiking'
import { Route as EatdoRestaurantsRouteImport } from './routes/_eatdo.restaurants'
import { Route as GroundsGroundsRouteImport } from './routes/_grounds.grounds'
import { Route as GroundsOrganicRouteImport } from './routes/_grounds.organic'
import { Route as GroundsRanchRouteImport } from './routes/_grounds.ranch'
import { Route as GroundsYardRouteImport } from './routes/_grounds.yard'
import { Route as HabitatHabitatRouteImport } from './routes/_habitat.habitat'
import { Route as HabitatTreesRouteImport } from './routes/_habitat.trees'
import { Route as HabitatWildlifeRouteImport } from './routes/_habitat.wildlife'
import { Route as RoomsGuarumoRouteImport } from './routes/_rooms.guarumo'
import { Route as RoomsRoomsRouteImport } from './routes/_rooms.rooms'
import { Route as RoomsSunriseRouteImport } from './routes/_rooms.sunrise'
import { Route as BaqueanoIndexRouteImport } from './routes/baqueano/index'
import { Route as BaqueanoBijagualWaterfallRouteImport } from './routes/baqueano/bijagual-waterfall'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EatdoRoute = EatdoRouteImport.update({
  id: '/_eatdo',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundsRoute = GroundsRouteImport.update({
  id: '/_grounds',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitatRoute = HabitatRouteImport.update({
  id: '/_habitat',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/_rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const EatdoEatdoRoute = EatdoEatdoRouteImport.update({
  id: '/eatdo',
  path: '/eatdo',
  getParentRoute: () => EatdoRoute,
} as any)
const EatdoHikingRoute = EatdoHikingRouteImport.update({
  id: '/hiking',
  path: '/hiking',
  getParentRoute: () => EatdoRoute,
} as any)
const EatdoRestaurantsRoute = EatdoRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => EatdoRoute,
} as any)
const GroundsGroundsRoute = GroundsGroundsRouteImport.update({
  id: '/grounds',
  path: '/grounds',
  getParentRoute: () => GroundsRoute,
} as any)
const GroundsOrganicRoute = GroundsOrganicRouteImport.update({
  id: '/organic',
  path: '/organic',
  getParentRoute: () => GroundsRoute,
} as any)
const GroundsRanchRoute = GroundsRanchRouteImport.update({
  id: '/ranch',
  path: '/ranch',
  getParentRoute: () => GroundsRoute,
} as any)
const GroundsYardRoute = GroundsYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => GroundsRoute,
} as any)
const HabitatHabitatRoute = HabitatHabitatRouteImport.update({
  id: '/habitat',
  path: '/habitat',
  getParentRoute: () => HabitatRoute,
} as any)
const HabitatTreesRoute = HabitatTreesRouteImport.update({
  id: '/trees',
  path: '/trees',
  getParentRoute: () => HabitatRoute,
} as any)
const HabitatWildlifeRoute = HabitatWildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => HabitatRoute,
} as any)
const RoomsGuarumoRoute = RoomsGuarumoRouteImport.update({
  id: '/guarumo',
  path: '/guarumo',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsRoomsRoute = RoomsRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsSunriseRoute = RoomsSunriseRouteImport.update({
  id: '/sunrise',
  path: '/sunrise',
  getParentRoute: () => RoomsRoute,
} as any)
const BaqueanoIndexRoute = BaqueanoIndexRouteImport.update({
  id: '/baqueano/',
  path: '/baqueano/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaqueanoBijagualWaterfallRoute =
  BaqueanoBijagualWaterfallRouteImport.update({
    id: '/baqueano/bijagual-waterfall',
    path: '/baqueano/bijagual-waterfall',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquire': typeof InquireRoute
  '/eatdo': typeof EatdoEatdoRoute
  '/hiking': typeof EatdoHikingRoute
  '/restaurants': typeof EatdoRestaurantsRoute
  '/grounds': typeof GroundsGroundsRoute
  '/organic': typeof GroundsOrganicRoute
  '/ranch': typeof GroundsRanchRoute
  '/yard': typeof GroundsYardRoute
  '/habitat': typeof HabitatHabitatRoute
  '/trees': typeof HabitatTreesRoute
  '/wildlife': typeof HabitatWildlifeRoute
  '/guarumo': typeof RoomsGuarumoRoute
  '/rooms': typeof RoomsRoomsRoute
  '/sunrise': typeof RoomsSunriseRoute
  '/baqueano/bijagual-waterfall': typeof BaqueanoBijagualWaterfallRoute
  '/baqueano/': typeof BaqueanoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquire': typeof InquireRoute
  '/eatdo': typeof EatdoEatdoRoute
  '/hiking': typeof EatdoHikingRoute
  '/restaurants': typeof EatdoRestaurantsRoute
  '/grounds': typeof GroundsGroundsRoute
  '/organic': typeof GroundsOrganicRoute
  '/ranch': typeof GroundsRanchRoute
  '/yard': typeof GroundsYardRoute
  '/habitat': typeof HabitatHabitatRoute
  '/trees': typeof HabitatTreesRoute
  '/wildlife': typeof HabitatWildlifeRoute
  '/guarumo': typeof RoomsGuarumoRoute
  '/rooms': typeof RoomsRoomsRoute
  '/sunrise': typeof RoomsSunriseRoute
  '/baqueano/bijagual-waterfall': typeof BaqueanoBijagualWaterfallRoute
  '/baqueano': typeof BaqueanoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_eatdo': typeof EatdoRouteWithChildren
  '/_grounds': typeof GroundsRouteWithChildren
  '/_habitat': typeof HabitatRouteWithChildren
  '/_rooms': typeof RoomsRouteWithChildren
  '/inquire': typeof InquireRoute
  '/_eatdo/eatdo': typeof EatdoEatdoRoute
  '/_eatdo/hiking': typeof EatdoHikingRoute
  '/_eatdo/restaurants': typeof EatdoRestaurantsRoute
  '/_grounds/grounds': typeof GroundsGroundsRoute
  '/_grounds/organic': typeof GroundsOrganicRoute
  '/_grounds/ranch': typeof GroundsRanchRoute
  '/_grounds/yard': typeof GroundsYardRoute
  '/_habitat/habitat': typeof HabitatHabitatRoute
  '/_habitat/trees': typeof HabitatTreesRoute
  '/_habitat/wildlife': typeof HabitatWildlifeRoute
  '/_rooms/guarumo': typeof RoomsGuarumoRoute
  '/_rooms/rooms': typeof RoomsRoomsRoute
  '/_rooms/sunrise': typeof RoomsSunriseRoute
  '/baqueano/bijagual-waterfall': typeof BaqueanoBijagualWaterfallRoute
  '/baqueano/': typeof BaqueanoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inquire'
    | '/eatdo'
    | '/hiking'
    | '/restaurants'
    | '/grounds'
    | '/organic'
    | '/ranch'
    | '/yard'
    | '/habitat'
    | '/trees'
    | '/wildlife'
    | '/guarumo'
    | '/rooms'
    | '/sunrise'
    | '/baqueano/bijagual-waterfall'
    | '/baqueano/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inquire'
    | '/eatdo'
    | '/hiking'
    | '/restaurants'
    | '/grounds'
    | '/organic'
    | '/ranch'
    | '/yard'
    | '/habitat'
    | '/trees'
    | '/wildlife'
    | '/guarumo'
    | '/rooms'
    | '/sunrise'
    | '/baqueano/bijagual-waterfall'
    | '/baqueano'
  id:
    | '__root__'
    | '/'
    | '/_eatdo'
    | '/_grounds'
    | '/_habitat'
    | '/_rooms'
    | '/inquire'
    | '/_eatdo/eatdo'
    | '/_eatdo/hiking'
    | '/_eatdo/restaurants'
    | '/_grounds/grounds'
    | '/_grounds/organic'
    | '/_grounds/ranch'
    | '/_grounds/yard'
    | '/_habitat/habitat'
    | '/_habitat/trees'
    | '/_habitat/wildlife'
    | '/_rooms/guarumo'
    | '/_rooms/rooms'
    | '/_rooms/sunrise'
    | '/baqueano/bijagual-waterfall'
    | '/baqueano/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EatdoRoute: typeof EatdoRouteWithChildren
  GroundsRoute: typeof GroundsRouteWithChildren
  HabitatRoute: typeof HabitatRouteWithChildren
  RoomsRoute: typeof RoomsRouteWithChildren
  InquireRoute: typeof InquireRoute
  BaqueanoBijagualWaterfallRoute: typeof BaqueanoBijagualWaterfallRoute
  BaqueanoIndexRoute: typeof BaqueanoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_eatdo': {
      id: '/_eatdo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EatdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_grounds': {
      id: '/_grounds'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_habitat': {
      id: '/_habitat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HabitatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rooms': {
      id: '/_rooms'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_eatdo/eatdo': {
      id: '/_eatdo/eatdo'
      path: '/eatdo'
      fullPath: '/eatdo'
      preLoaderRoute: typeof EatdoEatdoRouteImport
      parentRoute: typeof EatdoRoute
    }
    '/_eatdo/hiking': {
      id: '/_eatdo/hiking'
      path: '/hiking'
      fullPath: '/hiking'
      preLoaderRoute: typeof EatdoHikingRouteImport
      parentRoute: typeof EatdoRoute
    }
    '/_eatdo/restaurants': {
      id: '/_eatdo/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof EatdoRestaurantsRouteImport
      parentRoute: typeof EatdoRoute
    }
    '/_grounds/grounds': {
      id: '/_grounds/grounds'
      path: '/grounds'
      fullPath: '/grounds'
      preLoaderRoute: typeof GroundsGroundsRouteImport
      parentRoute: typeof GroundsRoute
    }
    '/_grounds/organic': {
      id: '/_grounds/organic'
      path: '/organic'
      fullPath: '/organic'
      preLoaderRoute: typeof GroundsOrganicRouteImport
      parentRoute: typeof GroundsRoute
    }
    '/_grounds/ranch': {
      id: '/_grounds/ranch'
      path: '/ranch'
      fullPath: '/ranch'
      preLoaderRoute: typeof GroundsRanchRouteImport
      parentRoute: typeof GroundsRoute
    }
    '/_grounds/yard': {
      id: '/_grounds/yard'
      path: '/yard'
      fullPath: '/yard'
      preLoaderRoute: typeof GroundsYardRouteImport
      parentRoute: typeof GroundsRoute
    }
    '/_habitat/habitat': {
      id: '/_habitat/habitat'
      path: '/habitat'
      fullPath: '/habitat'
      preLoaderRoute: typeof HabitatHabitatRouteImport
      parentRoute: typeof HabitatRoute
    }
    '/_habitat/trees': {
      id: '/_habitat/trees'
      path: '/trees'
      fullPath: '/trees'
      preLoaderRoute: typeof HabitatTreesRouteImport
      parentRoute: typeof HabitatRoute
    }
    '/_habitat/wildlife': {
      id: '/_habitat/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof HabitatWildlifeRouteImport
      parentRoute: typeof HabitatRoute
    }
    '/_rooms/guarumo': {
      id: '/_rooms/guarumo'
      path: '/guarumo'
      fullPath: '/guarumo'
      preLoaderRoute: typeof RoomsGuarumoRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/_rooms/rooms': {
      id: '/_rooms/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRoomsRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/_rooms/sunrise': {
      id: '/_rooms/sunrise'
      path: '/sunrise'
      fullPath: '/sunrise'
      preLoaderRoute: typeof RoomsSunriseRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/baqueano/': {
      id: '/baqueano/'
      path: '/baqueano'
      fullPath: '/baqueano/'
      preLoaderRoute: typeof BaqueanoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baqueano/bijagual-waterfall': {
      id: '/baqueano/bijagual-waterfall'
      path: '/baqueano/bijagual-waterfall'
      fullPath: '/baqueano/bijagual-waterfall'
      preLoaderRoute: typeof BaqueanoBijagualWaterfallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EatdoRouteChildren {
  EatdoEatdoRoute: typeof EatdoEatdoRoute
  EatdoHikingRoute: typeof EatdoHikingRoute
  EatdoRestaurantsRoute: typeof EatdoRestaurantsRoute
}

const EatdoRouteChildren: EatdoRouteChildren = {
  EatdoEatdoRoute: EatdoEatdoRoute,
  EatdoHikingRoute: EatdoHikingRoute,
  EatdoRestaurantsRoute: EatdoRestaurantsRoute,
}

const EatdoRouteWithChildren = EatdoRoute._addFileChildren(EatdoRouteChildren)

interface GroundsRouteChildren {
  GroundsGroundsRoute: typeof GroundsGroundsRoute
  GroundsOrganicRoute: typeof GroundsOrganicRoute
  GroundsRanchRoute: typeof GroundsRanchRoute
  GroundsYardRoute: typeof GroundsYardRoute
}

const GroundsRouteChildren: GroundsRouteChildren = {
  GroundsGroundsRoute: GroundsGroundsRoute,
  GroundsOrganicRoute: GroundsOrganicRoute,
  GroundsRanchRoute: GroundsRanchRoute,
  GroundsYardRoute: GroundsYardRoute,
}

const GroundsRouteWithChildren =
  GroundsRoute._addFileChildren(GroundsRouteChildren)

interface HabitatRouteChildren {
  HabitatHabitatRoute: typeof HabitatHabitatRoute
  HabitatTreesRoute: typeof HabitatTreesRoute
  HabitatWildlifeRoute: typeof HabitatWildlifeRoute
}

const HabitatRouteChildren: HabitatRouteChildren = {
  HabitatHabitatRoute: HabitatHabitatRoute,
  HabitatTreesRoute: HabitatTreesRoute,
  HabitatWildlifeRoute: HabitatWildlifeRoute,
}

const HabitatRouteWithChildren =
  HabitatRoute._addFileChildren(HabitatRouteChildren)

interface RoomsRouteChildren {
  RoomsGuarumoRoute: typeof RoomsGuarumoRoute
  RoomsRoomsRoute: typeof RoomsRoomsRoute
  RoomsSunriseRoute: typeof RoomsSunriseRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsGuarumoRoute: RoomsGuarumoRoute,
  RoomsRoomsRoute: RoomsRoomsRoute,
  RoomsSunriseRoute: RoomsSunriseRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EatdoRoute: EatdoRouteWithChildren,
  GroundsRoute: GroundsRouteWithChildren,
  HabitatRoute: HabitatRouteWithChildren,
  RoomsRoute: RoomsRouteWithChildren,
  InquireRoute: InquireRoute,
  BaqueanoBijagualWaterfallRoute: BaqueanoBijagualWaterfallRoute,
  BaqueanoIndexRoute: BaqueanoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
